version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    command: mysqld --sql_mode="" --innodb-flush-log-at-trx-commit=0
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./app/sql:/docker-entrypoint-initdb.d/:ro
volumes: 
  db-config:
  db-data: