version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./app/sql:/docker-entrypoint-initdb.d/:ro
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data: